2022-03-01 18:26:32,490 INFO    MainThread:7364 [wandb_setup.py:_flush():75] Loading settings from C:\Users\User\.config\wandb\settings
2022-03-01 18:26:32,490 INFO    MainThread:7364 [wandb_setup.py:_flush():75] Loading settings from E:\Python\Mahdis Projects\assignment-41\wandb\settings
2022-03-01 18:26:32,491 INFO    MainThread:7364 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-01 18:26:32,491 INFO    MainThread:7364 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-01 18:26:32,491 INFO    MainThread:7364 [wandb_init.py:_log_setup():386] Logging user logs to E:\Python\Mahdis Projects\assignment-41\wandb\run-20220301_182630-6liotvaa\logs\debug.log
2022-03-01 18:26:32,492 INFO    MainThread:7364 [wandb_init.py:_log_setup():387] Logging internal logs to E:\Python\Mahdis Projects\assignment-41\wandb\run-20220301_182630-6liotvaa\logs\debug-internal.log
2022-03-01 18:26:32,492 INFO    MainThread:7364 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001B2B5D777C0>
2022-03-01 18:26:32,492 INFO    MainThread:7364 [wandb_init.py:init():420] calling init triggers
2022-03-01 18:26:32,492 INFO    MainThread:7364 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-03-01 18:26:32,492 INFO    MainThread:7364 [wandb_init.py:init():471] starting backend
2022-03-01 18:26:32,492 INFO    MainThread:7364 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-03-01 18:26:32,496 INFO    MainThread:7364 [backend.py:ensure_launched():219] starting backend process...
2022-03-01 18:26:32,611 INFO    MainThread:7364 [backend.py:ensure_launched():224] started backend process with pid: 2868
2022-03-01 18:26:32,612 INFO    MainThread:7364 [wandb_init.py:init():480] backend started and connected
2022-03-01 18:26:32,615 INFO    MainThread:7364 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-03-01 18:26:32,615 INFO    MainThread:7364 [wandb_init.py:init():550] updated telemetry
2022-03-01 18:26:32,618 INFO    MainThread:7364 [wandb_init.py:init():581] communicating current version
2022-03-01 18:26:35,312 INFO    MainThread:7364 [wandb_init.py:init():586] got version response 
2022-03-01 18:26:35,312 INFO    MainThread:7364 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-01 18:27:05,315 INFO    MainThread:7364 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-03-01 18:27:05,315 ERROR   MainThread:7364 [wandb_init.py:init():601] backend process timed out
2022-03-01 18:27:05,315 ERROR   MainThread:7364 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-03-01 18:27:05,362 ERROR   MainThread:7364 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_init.py", line 951, in init
    run = wi.init()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_init.py", line 614, in init
    backend.cleanup()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\backend\backend.py", line 248, in cleanup
    self.interface.join()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 458, in join
    super().join()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\interface\interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
